apiVersion: apps/v1
kind: Deployment
metadata:
  name: partners-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: partners-service
  template:
    metadata:
      labels:
        app: partners-service
    spec:
      containers:
      - name: partners-service
        image: ethanhaller5/partners-service:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
