apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recruitment-service
  template:
    metadata:
      labels:
        app: recruitment-service
    spec:
      containers:
      - name: recruitment-service
        image: ethanhaller5/recruitment-service:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
